# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Eric Lesiuta
"""Install or print shell tab-completion (`agent6 completions`).

`argcomplete.shellcode()` emits the registration, so no register script has to be
on PATH. Bash and zsh get the script under the config dir and one marker-guarded
`source` line in their rc file, rerunnable without duplicates; fish and xonsh get
a file in their auto-load dir. Xonsh is no argcomplete target, so its file is a
small completer that drives the argcomplete protocol itself. The shell is the
nearest known one up the process tree, else `$SHELL`.
"""

from __future__ import annotations

import os
import shlex
from pathlib import Path

from argcomplete.shell_integration import shellcode

from agent6.errors import read_operator_file
from agent6.paths import global_config_dir
from agent6.ui.cli._common import error

SHELLS = ("bash", "zsh", "fish", "xonsh")
_MARK_BEGIN = "# >>> agent6 completions >>>"
_MARK_END = "# <<< agent6 completions <<<"
_PROC = Path("/proc")  # patched in tests

# Registered ahead of xonsh's default completer so it wins for agent6; a no-op elsewhere.
_XONSH_SCRIPT = """\
# agent6 tab-completion for xonsh, generated by `agent6 completions xonsh`.
# It asks the agent6 on PATH for candidates at completion time (the
# argcomplete protocol: request in env vars, answer in a side file), so it
# needs no regeneration when agent6's arguments change.
import os
import shlex
import subprocess
import tempfile

from xonsh.built_ins import XSH
from xonsh.completers import completer
from xonsh.completers.tools import (
    RichCompletion,
    contextual_command_completer,
)


@contextual_command_completer
def _agent6_completer(context):
    if not context.args or os.path.basename(context.args[0].value) != "agent6":
        return None
    line = context.text_before_cursor
    handle = tempfile.NamedTemporaryFile(delete=False)
    handle.close()
    env = {
        **XSH.env.detype(),
        "_ARGCOMPLETE": "1",
        "_ARGCOMPLETE_IFS": "\\n",
        "_ARGCOMPLETE_DFS": "\\t",
        "_ARGCOMPLETE_SUPPRESS_SPACE": "1",
        "_ARGCOMPLETE_SHELL": "fish",
        "_ARGCOMPLETE_STDOUT_FILENAME": handle.name,
        "COMP_LINE": line,
        "COMP_POINT": str(len(line)),
    }
    try:
        try:
            subprocess.run(
                [context.args[0].value],
                env=env,
                timeout=10,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except (OSError, subprocess.TimeoutExpired):
            # agent6 is an alias/abbrev rather than a binary, or it hung:
            # no candidates, and no exception splashed across the prompt.
            return None
        with open(handle.name, encoding="utf-8") as out:
            output = out.read()
    finally:
        os.unlink(handle.name)
    # argcomplete already filtered by the prefix (COMP_POINT is the true
    # cursor); an empty set falls through to xonsh's own completers (e.g.
    # paths). Values the shell would split are quoted, on the bare value, so
    # a trailing-sep directory is still detected and keeps no-space completing
    # into itself.
    candidates = set()
    for entry in output.splitlines():
        if not entry.strip():
            continue
        value, _, desc = entry.strip().partition("\\t")
        value = value.strip()
        candidates.add(
            RichCompletion(
                shlex.quote(value),
                description=desc.strip(),
                append_space=not value.endswith(os.sep),
            )
        )
    return candidates


completer.add_one_completer("agent6", _agent6_completer, "start")
"""


def detect_shell() -> str:
    """Return the shell this command was launched from.

    The nearest known shell up the process tree, since `$SHELL` is the login shell
    and the direct parent can be a wrapper like `uv`; `$SHELL`'s basename when the
    walk finds nothing (no `/proc`).
    """
    pid = os.getppid()
    for _ in range(10):
        try:
            comm = (_PROC / str(pid) / "comm").read_text(encoding="utf-8").strip()
            stat = (_PROC / str(pid) / "stat").read_text(encoding="utf-8")
        except OSError:
            break
        if comm in SHELLS:
            return comm
        # stat is "pid (comm) state ppid ..."; comm may hold parens, so split at the last ")".
        try:
            pid = int(stat.rsplit(")", 1)[1].split()[1])
        except (IndexError, ValueError):
            break
        if pid <= 1:
            break
    return Path(os.environ.get("SHELL", "")).name


def _rc_path(shell: str) -> Path:
    """Return the shell's rc file; zsh reads it from `$ZDOTDIR` when set."""
    if shell == "bash":
        return Path.home() / ".bashrc"
    return Path(os.environ.get("ZDOTDIR") or Path.home()) / ".zshrc"


# Where a shell that auto-loads its completions reads ours, under the config home.
_AUTOLOAD = {
    "fish": ("fish", "completions", "agent6.fish"),
    "xonsh": ("xonsh", "rc.d", "agent6.xsh"),
}


def _autoload_path(shell: str) -> Path:
    """Return the auto-loaded file's path for fish or xonsh."""
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg) if xdg else Path.home() / ".config"
    return base.joinpath(*_AUTOLOAD[shell])


def _install_bash_zsh(shell: str, code: str) -> int:
    """Write the script under the config dir and source it from the rc file's marker block.

    Args:
        shell: `bash` or `zsh`.
        code: The registration script.

    Returns:
        The exit code; 2 when the rc file's marker block is malformed.
    """
    script = global_config_dir() / f"completions.{shell}"
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(code, encoding="utf-8")
    rc = _rc_path(shell)
    # The path lands in shell text the operator's shell sources; quoted, a metacharacter is inert.
    q = shlex.quote(str(script))
    block = f"\n{_MARK_BEGIN}\n[ -f {q} ] && source {q}  # agent6 tab-completion\n{_MARK_END}\n"
    existing = read_operator_file(rc) if rc.exists() else ""
    if _MARK_BEGIN in existing:
        if (
            existing.count(_MARK_BEGIN) != 1
            or existing.count(_MARK_END) != 1
            or existing.index(_MARK_END) < existing.index(_MARK_BEGIN)
        ):
            # agent6 edits only its one marker block; a mangled one is the operator's to fix.
            error(
                f"{rc} holds malformed agent6 completion markers"
                f" ({_MARK_BEGIN} / {_MARK_END}); fix or remove them and rerun."
            )
            return 2
        start = existing.index(_MARK_BEGIN)
        end = existing.index(_MARK_END) + len(_MARK_END)
        current = existing[start:end]
        wanted = block.strip("\n")
        if current == wanted:
            print(f"[agent6] refreshed {script} (already sourced from {rc})")
        else:
            # A moved config home leaves the block pointing at the old script path.
            rc.write_text(existing[:start] + wanted + existing[end:], encoding="utf-8")
            print(f"[agent6] updated the source path in {rc}")
    else:
        with rc.open("a", encoding="utf-8") as fh:
            fh.write(block)
        print(f"[agent6] wrote {script} and added a source line to {rc}")
    print(f"[agent6] activate now with: source {rc}   (or start a new shell: exec $SHELL)")
    return 0


def _install_autoloaded(code: str, target: Path, shell: str) -> int:
    """Return 0 after writing the auto-loaded file for fish or xonsh."""
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(code, encoding="utf-8")
    print(f"[agent6] wrote {target} ({shell} loads it automatically)")
    return 0


def cmd_completions(shell_arg: str | None, *, print_only: bool) -> int:
    """Install the shell's completion, or print it.

    Args:
        shell_arg: The shell named on the command line; detected when None.
        print_only: Print the script instead of installing it.

    Returns:
        The exit code; 2 for an unknown shell.
    """
    shell = shell_arg or detect_shell()
    if shell not in SHELLS:
        detected = f" (detected {shell!r})" if shell else ""
        error(
            f"unsupported or unknown shell{detected}."
            f" Pass one of: agent6 completions {'|'.join(SHELLS)}"
        )
        return 2
    # Xonsh is not an argcomplete backend; it gets a generated completer.
    code = _XONSH_SCRIPT if shell == "xonsh" else shellcode(["agent6"], shell=shell)
    if print_only:
        print(code)
        return 0
    if shell in _AUTOLOAD:
        return _install_autoloaded(code, _autoload_path(shell), shell)
    return _install_bash_zsh(shell, code)
