#!/usr/bin/env bash
# Real-world head-to-head: claude-code on the same fixtures as
# `bench/realworld/run_realworld.sh`. Each task clones the upstream repo,
# applies the agent6 "break", hands the resulting TASK.md to claude-code in
# non-interactive --print mode (with --dangerously-skip-permissions so it
# can edit the worktree), then runs the same verify_command on the host
# and records cost/tokens/wall.
#
# Usage:
#   CLAUDE_TOTAL_BUDGET_USD=5.00 BENCH_ROOT=/tmp/agent6-realworld-claude \
#     bash bench/realworld/run_realworld_claude.sh
#
# Pair this with a prior agent6 run at $AGENT6_BENCH_ROOT (default
# /tmp/agent6-realworld-ab) to render a side-by-side summary.

set -euo pipefail

REPO="${AGENT6_REPO:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
BENCH_ROOT="${BENCH_ROOT:-/tmp/agent6-realworld-claude}"
AGENT6_BENCH_ROOT="${AGENT6_BENCH_ROOT:-/tmp/agent6-realworld-ab}"
PER_TASK_BUDGET_USD="${PER_TASK_BUDGET_USD:-1.00}"
CLAUDE_TOTAL_BUDGET_USD="${CLAUDE_TOTAL_BUDGET_USD:-5.00}"
CLAUDE_MODEL="${CLAUDE_MODEL:-claude-sonnet-4-5}"
CLAUDE_BIN="${CLAUDE_BIN:-$HOME/.npm-global/bin/claude}"
PYTHON_BIN="${PYTHON_BIN:-$(command -v python3)}"
export PYTHON_BIN

cd "$REPO"
[ -x "$CLAUDE_BIN" ] || { echo "claude-code not found at $CLAUDE_BIN" >&2; exit 1; }
mkdir -p "$BENCH_ROOT/_logs"

# Reuse setup_task from run_realworld.sh by sourcing the helpers section.
# To keep things simple, we duplicate the minimum logic here instead of
# refactoring the existing harness.
setup_task() {
  local task_json="$1" dir="$2"
  python3 - "$task_json" "$dir" "$PYTHON_BIN" <<'PY'
import json, os, subprocess, sys
from pathlib import Path
task = json.load(open(sys.argv[1]))
dir = Path(sys.argv[2])
python_bin = sys.argv[3]
if dir.exists():
    subprocess.run(["rm", "-rf", str(dir)], check=True)
# Two task schemas, same as bench/realworld/run_realworld.sh:
#   - upstream clone:   has "repo_url" + "commit" + "break"
#   - self-contained:   has "files" {relpath: content} authored inline
if "repo_url" in task:
    subprocess.run(
        ["git", "clone", "-q", "--depth", "1", "-b", task["commit"], task["repo_url"], str(dir)],
        check=True,
    )
else:
    subprocess.run(["git", "init", "--quiet", str(dir)], check=True)
    for relpath, content in task.get("files", {}).items():
        p = dir / relpath
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
# Configure git identity (clone leaves the directory bare of user config).
subprocess.run(["git", "-C", str(dir), "config", "user.email", "bench@agent6"], check=True)
subprocess.run(["git", "-C", str(dir), "config", "user.name", "bench"], check=True)
# Seed commit for self-contained tasks so breaks apply on a committed worktree.
if "repo_url" not in task:
    subprocess.run(["git", "-C", str(dir), "add", "-A"], check=True)
    subprocess.run(["git", "-C", str(dir), "commit", "-q", "-m", "bench: seed"], check=True)
for entry in task.get("break", []):
    p = dir / entry["path"]
    txt = p.read_text()
    assert entry["find"] in txt, f"break.find not found in {p}"
    p.write_text(txt.replace(entry["find"], entry["replace"], 1))
subprocess.run(["git", "-C", str(dir), "add", "-A"], check=True)
_dirty = subprocess.run(["git", "-C", str(dir), "diff", "--cached", "--quiet"]).returncode
if _dirty != 0:
    subprocess.run(["git", "-C", str(dir), "commit", "-q", "-m", "bench: introduce gap"], check=True)
(dir / "TASK.md").write_text(task["task_md"])
agents = dir / "AGENTS.md"
if not agents.exists():
    agents.write_text(
        "# Project conventions (auto-generated by agent6 realworld bench)\n\n"
        "This is a synthetic fix-the-gap scenario. The relevant function has been\n"
        "replaced with `raise NotImplementedError(\"agent6-realworld: restore \"\n"
        "\"this implementation\")`.\n\n"
        "Your job is to restore the original implementation so the configured\n"
        "verify_command passes. The verify_command runs only the test(s) that\n"
        "exercise the broken function — keep your change minimal and do not\n"
        "modify test files.\n"
    )
subprocess.run(["git", "-C", str(dir), "add", "-A"], check=True)
subprocess.run(["git", "-C", str(dir), "commit", "-q", "-m", "bench: add TASK.md"], check=True)
# Install task dependencies.
for cmd in task.get("install", []):
    argv = [python_bin if t == "python3" else t for t in cmd]
    subprocess.run(argv, cwd=str(dir), check=True)
PY
}

total_cost=0
total_wall=0
pass=0
total=0
results_file="$BENCH_ROOT/results_claude.md"

for task_json in "$REPO"/bench/realworld/tasks/*.json; do
  name=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['name'])" "$task_json")
  if [ -n "${AGENT6_REALWORLD_TASK_FILTER:-}" ]; then
    match=0
    IFS=',' read -ra _filters <<< "$AGENT6_REALWORLD_TASK_FILTER"
    for f in "${_filters[@]}"; do
      case "$name" in *"$f"*) match=1; break ;; esac
    done
    [ "$match" = 1 ] || { echo "[skip] $name (not in TASK_FILTER)"; continue; }
  fi
  desc=$(python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['description'])" "$task_json")
  verify_cmd_json=$(python3 -c "import json,sys; print(json.dumps(json.load(open(sys.argv[1]))['verify_command']))" "$task_json")
  dir="$BENCH_ROOT/${name}_claude"
  logdir="$BENCH_ROOT/_logs/${name}_claude"
  mkdir -p "$logdir"

  echo
  echo "================================================================"
  echo "TASK: $name [claude-code]"
  echo "  $desc"
  echo "================================================================"

  setup_task "$task_json" "$dir"

  task_text=$(cat "$dir/TASK.md")

  start_ns=$(date +%s%N)
  set +e
  ( cd "$dir" && "$CLAUDE_BIN" \
      --print \
      --dangerously-skip-permissions \
      --model "$CLAUDE_MODEL" \
      --output-format json \
      --max-budget-usd "$PER_TASK_BUDGET_USD" \
      "$task_text" \
  ) > "$logdir/claude.json" 2> "$logdir/claude.stderr"
  agent_exit=$?
  set -e
  end_ns=$(date +%s%N)
  wall_s=$(awk -v s="$start_ns" -v e="$end_ns" 'BEGIN{printf "%.1f", (e-s)/1e9}')

  # Verify on host (same as the agent6 harness does).
  set +e
  ( cd "$dir" && python3 -c "import json,sys; cmd=json.loads(sys.argv[1]); import subprocess; sys.exit(subprocess.call(cmd))" "$verify_cmd_json" ) \
      > "$logdir/final_verify.txt" 2>&1
  verify=$?
  set -e

  cost=$(python3 -c "import json,sys; d=json.load(open('$logdir/claude.json')); print(d.get('total_cost_usd', d.get('cost_usd', 0)))" 2>/dev/null || echo 0)
  duration_api=$(python3 -c "import json,sys; d=json.load(open('$logdir/claude.json')); print(d.get('duration_ms', 0)/1000)" 2>/dev/null || echo 0)
  turns=$(python3 -c "import json,sys; d=json.load(open('$logdir/claude.json')); print(d.get('num_turns', d.get('turns', 0)))" 2>/dev/null || echo 0)
  in_tok=$(python3 -c "import json,sys; d=json.load(open('$logdir/claude.json')); u=d.get('usage', {}); print(u.get('input_tokens', 0))" 2>/dev/null || echo 0)
  out_tok=$(python3 -c "import json,sys; d=json.load(open('$logdir/claude.json')); u=d.get('usage', {}); print(u.get('output_tokens', 0))" 2>/dev/null || echo 0)

  cat > "$logdir/result.json" <<EOF
{
  "task": "$name",
  "runner": "claude-code",
  "agent_exit": $agent_exit,
  "wall_seconds": $wall_s,
  "verify_pass": $([ $verify -eq 0 ] && echo true || echo false),
  "cost_usd": $cost,
  "duration_api_s": $duration_api,
  "turns": $turns,
  "input_tokens": $in_tok,
  "output_tokens": $out_tok
}
EOF

  echo "  agent_exit=$agent_exit  verify=$([ $verify -eq 0 ] && echo PASS || echo FAIL)  wall=${wall_s}s  cost=\$${cost}  turns=${turns}"

  total_cost=$(awk -v a="$total_cost" -v b="$cost" 'BEGIN{printf "%.4f", a+b}')
  total_wall=$(awk -v a="$total_wall" -v b="$wall_s" 'BEGIN{printf "%.1f", a+b}')
  total=$((total+1))
  [ $verify -eq 0 ] && pass=$((pass+1))

  over=$(awk -v a="$total_cost" -v b="$CLAUDE_TOTAL_BUDGET_USD" 'BEGIN{print (a>b)?1:0}')
  if [ "$over" = "1" ]; then
    echo "TOTAL COST $total_cost EXCEEDED CAP $CLAUDE_TOTAL_BUDGET_USD — aborting" >&2
    exit 2
  fi
done

{
  echo "# Real-world head-to-head: claude-code"
  echo
  echo "Model: $CLAUDE_MODEL. Per-task budget cap: \$$PER_TASK_BUDGET_USD."
  echo
  printf "| Task | verify | wall | cost | turns | in toks | out toks |\n"
  printf "|------|--------|------|------|-------|---------|----------|\n"
  for d in "$BENCH_ROOT"/_logs/*_claude/; do
    [ -f "$d/result.json" ] || continue
    python3 -c "
import json
r = json.load(open('$d/result.json'))
print(f'| {r[\"task\"]} | {\"PASS\" if r[\"verify_pass\"] else \"FAIL\"} | {r[\"wall_seconds\"]:.1f}s | \${r[\"cost_usd\"]:.4f} | {r[\"turns\"]} | {r[\"input_tokens\"]} | {r[\"output_tokens\"]} |')
"
  done
  echo
  echo "**Total: $pass / $total verify pass, \$$total_cost, ${total_wall}s wall.**"
} > "$results_file"

echo
echo "Summary written to $results_file"
echo "Total: $pass/$total PASS, \$$total_cost, ${total_wall}s wall"
